name: Build Load Tester

on:
  push:
    branches: [ "main" ]
    paths:
      - 'load-test/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Calculate Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./load-test
          push: true
          tags: |
            ttl.sh/my-guestbook-loader:${{ steps.vars.outputs.sha_short }}
            ttl.sh/my-guestbook-loader:latest

      - name: Update Kubernetes Manifest
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

          # Update yaml with new SHA tag
          sed -i "s|image: ttl.sh/my-guestbook-loader:.*|image: ttl.sh/my-guestbook-loader:${{ steps.vars.outputs.sha_short }}|g" load-test/load-test-job.yaml

          # Push changes back to repo
          git add load-test/load-test-job.yaml
          git commit -m "CD: Update image tag to ${{ steps.vars.outputs.sha_short }}"
          git push
